### ISSUE TITLE
Using a cwd module before initialization

### ISSUE THREAD

**Issue by ilyamore88** [shelfio/jest-mongodb#218]
I tried to create MongoDB instance with `jest-mongodb-config.js`, but I always got random `mongoUri` in `globalConfig.json` like this:
```
"mongoUri":"mongodb://127.0.0.1:62212/6062f011-b0af-4bd3-89be-cd1ed47c4c37?"
```
When I added `console.log(e)` in `getMongodbMemoryOptions()` function, I got this:
```
ReferenceError: Cannot access 'cwd' before initialization
    at getMongodbMemoryOptions (D:\WebStormProjects\hawk.mono\api\node_modules\@shelf\jest-mongodb\setup.js:34:58)
    at Object.<anonymous> (D:\WebStormProjects\hawk.mono\api\node_modules\@shelf\jest-mongodb\setup.js:6:48)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.newLoader [as .js] (D:\WebStormProjects\hawk.mono\api\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at ScriptTransformer.requireAndTranspileModule (D:\WebStormProjects\hawk.mono\api\node_modules\@jest\transform\build\ScriptTransformer.js:676:20)
```
You need to init cwd before creating MongodbMemoryServer.

**Comment by vladgolubev** [comment]
Fixed in 1.2.2
