### ISSUE TITLE
Mongo instance on Bitbucket pipelines

### ISSUE THREAD

**Issue by RahulReddy75** [shelfio/jest-mongodb#247]
Tried exactly as given in https://jestjs.io/docs/en/mongodb. The local integration tests work fine but the tests fail on the bitbucket pipeline (uses alpine image). 

This is the error generated:
```
Starting the instance failed, please enable debug for more infomation
TypeError: Cannot read property 'toString' of undefined
    at MongoInstance._launchKiller (/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:259:22)
    at MongoInstance.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:148:51)
    at step (/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:44:23)
    at Object.next (/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:25:53)
    at fulfilled (/opt/atlassian/pipelines/agent/build/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:16:58)
error Command failed with exit code 1. 
```
Not able to understand from the documentation if I should do something different for this to work on pipelines. 
what am I missing?

**Comment by RahulReddy75** [comment]
Fixed this by directly using the original library (mongodb-memory-server) and adding a different node image for that particular step in pipeline.
