### ISSUE TITLE
bug: it break after updated to mongodb-memory-server@7.0.0

### ISSUE THREAD

**Issue by climba03003** [shelfio/jest-mongodb#282]
Error Message:
```
TypeError: Jest: Got error running globalSetup - <src>/node_modules/@shelf/jest-mongodb/setup.js, reason: MongodbMemoryServer.default is not a constructor
    at Object.<anonymous> (<src>/node_modules/@shelf/jest-mongodb/setup.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader (<src>/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at requireOrImportModule (<src>/node_modules/jest-util/build/requireOrImportModule.js:53:28)
    at ScriptTransformer.requireAndTranspileModule (<src>/node_modules/@jest/transform/build/ScriptTransformer.js:885:66)
error Command failed with exit code 1.
```

**Comment by climba03003** [comment]
I can see that the CircleCI also failed with the same message.

**Comment by vladgolubev** [comment]
Thanks, I'll fix it asap

**Comment by vladgolubev** [comment]
Fixed in 1.3.1 https://github.com/shelfio/jest-mongodb/releases/tag/v1.3.1

**Comment by climba03003** [comment]
Thanks for the fast response.
