### ISSUE TITLE
Does not work with Node.js v16

### ISSUE THREAD

**Issue by crobinson42** [shelfio/jest-mongodb#293]
This package only works with Node.js v12 & v14.

Here is the error in Node.js v16 environment:

```
> npx jest

Starting the instance failed, enable debug for more information
Error: Jest: Got error running globalSetup - /domain-impl-server/node_modules/@shelf/jest-mongodb/setup.js, reason: Instance Exited before being ready and without throwing an error!
    at MongoInstance.<anonymous> (/domain-impl-server/node_modules/@shelf/jest-mongodb/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:134:25)
    at Object.onceWrapper (node:events:514:26)
    at MongoInstance.emit (node:events:394:28)
    at MongoInstance.closeHandler (/domain-impl-server/node_modules/@shelf/jest-mongodb/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:275:14)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by vladgolubev** [comment]
This error originates from MongoDB Memory Server

https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/util/MongoInstance.ts#L273

Maybe it's better to open issue in that repo instead

**Comment by crobinson42** [comment]
@vladgolubev how about we bump mongodb-memory-server to the latest version 7.3.6 in this package and give it a test to see if that solves the issue. If that doesn't work then we can open an issue upstream in that repo 👍

**Comment by vladgolubev** [comment]
@crobinson42 fair assumption. Check out https://github.com/shelfio/jest-mongodb/releases/tag/v2.0.2 with the latest version of `mongodb-memory-server`

**Comment by crobinson42** [comment]
@vladgolubev I have verified v2.0.2 works with node v16.

There is an impending PR that should be merge also to make the package fully compatible [up to date] with node v16: #290 perhaps you can merge and bump to v2.0.3? 🙏

**Comment by vladgolubev** [comment]
@crobinson42 sure, here it is https://github.com/shelfio/jest-mongodb/releases/tag/v2.0.3

**Comment by climba03003** [comment]
Thanks, the latest version solved the problem on node v16.

**Comment by crobinson42** [comment]
It works locally, however, I'm still seeing this issue in the CI environment: 

```
> jest
Starting the instance failed, enable debug for more information
Error: Jest: Got error running globalSetup - /opt/atlassian/pipelines/agent/build/node_modules/@shelf/jest-mongodb/setup.js, reason: Instance Exited before being ready and without throwing an error!
```

**Comment by crobinson42** [comment]
My custom image with 4.4 doesn’t use 4.4 in jest mongodb tests, i simply based on that image because it’s sure to have the required deps. I look forward to what you find in your investigation. Thanks!
