### ISSUE TITLE
MongoMemoryServer failing to install binary on macos (needs upgrade to v8 for fix)

### ISSUE THREAD

**Issue by the-vampiire** [shelfio/jest-mongodb#324]
receiving following error:

```sh
Error: Jest: Got error running globalSetup - /workspace/node_modules/@shelf/jest-mongodb/setup.js, reason: Status Code is 403 (MongoDB's 404)
This means that the requested version-platform combination doesn't exist
  Used Url: "https://fastdl.mongodb.org/linux/mongodb-linux-arm64-debian10-5.0.3.tgz"
Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
```

with following `jest-mongodb-config.js`

```js
module.exports = {
  mongodbMemoryServerOptions: {
    binary: {
      version: '5.0.3',
      skipMD5: true,
    },
    instance: {
      dbName: 'jest',
    },
    autoStart: false,
  },
};
```

this looks to be due to a [regex parsing error for macos (mongodb-memory-server)](https://github.com/nodkz/mongodb-memory-server/pull/562). a fix was merged in [v8.0.0](https://github.com/nodkz/mongodb-memory-server/pull/562#issuecomment-956295764)

`jest-mongodb` is using [v7.6.3](https://github.com/shelfio/jest-mongodb/blob/1a41aa8204f166bec25f8f31b699d9c4d73ce04c/package.json#L47)

**Comment by the-vampiire** [comment]
i forked `jest-mongodb` and updated `mongodb-memory-server` to `8.1.0`

> test

```sh
❯ npm run test

> @shelf/jest-mongodb@2.2.0 test
> jest

 PASS  ./mongo-parallelism3.test.js
 PASS  ./mongo-insert.test.js
 PASS  ./mongo-aggregate.test.js
 PASS  ./mongo-parallelism2.test.js
 PASS  ./mongo-parallelism.test.js

Test Suites: 5 passed, 5 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        0.639 s
Ran all test suites.
```

> test:repl

```sh

❯ npm run test:repl

> @shelf/jest-mongodb@2.2.0 test:repl
> MONGO_MEMORY_SERVER_FILE=jest-mongodb-config-repl.js jest

 FAIL  ./mongo-parallelism3.test.js
  ● parallelism: third worker › should have separate database

    MongoBulkWriteError: Primary stepped down while waiting for replication

      at handleMongoWriteConcernError (node_modules/mongodb/src/bulk/common.ts:694:5)

 PASS  ./mongo-aggregate.test.js
 PASS  ./mongo-parallelism2.test.js
 PASS  ./mongo-insert.test.js
 PASS  ./mongo-parallelism.test.js

Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        16.547 s
Ran all test suites.
```

**Comment by the-vampiire** [comment]
failing test persists in both `v8.0.0` and `v8.1.0`

```sh
 FAIL  ./mongo-parallelism3.test.js
  ● parallelism: third worker › should have separate database

    MongoBulkWriteError: Primary stepped down while waiting for replication

      at handleMongoWriteConcernError (node_modules/mongodb/src/bulk/common.ts:694:5)
```

happy to help fix if you can give me some direction

**Comment by the-vampiire** [comment]
upgrading `mongodb` to latest `4.3.0` then causes failure in `parallelism2` but `parallelism3` passes

```sh
❯ npm run test:repl

> @shelf/jest-mongodb@2.2.0 test:repl
> MONGO_MEMORY_SERVER_FILE=jest-mongodb-config-repl.js jest

 FAIL  ./mongo-parallelism2.test.js (5.056 s)
  ● parallelism: second worker › should have separate database

    MongoBulkWriteError: Primary stepped down while waiting for replication

      at handleMongoWriteConcernError (node_modules/mongodb/src/bulk/common.ts:694:5)

 PASS  ./mongo-insert.test.js (8.059 s)
 PASS  ./mongo-parallelism3.test.js
 PASS  ./mongo-aggregate.test.js
 PASS  ./mongo-parallelism.test.js

Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        15.554 s
Ran all test suites.
```

**Comment by the-vampiire** [comment]
`mongodb` `4.3.0`

`mongodb-memory-server` `8.1.0`

failure on `parallelism3`

```sh
❯ npm i && npm run test && npm run test:repl

added 1 package, changed 2 packages, and audited 825 packages in 3s

111 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> @shelf/jest-mongodb@2.2.0 test
> jest

 PASS  ./mongo-parallelism.test.js
 PASS  ./mongo-parallelism3.test.js
 PASS  ./mongo-parallelism2.test.js
 PASS  ./mongo-insert.test.js
 PASS  ./mongo-aggregate.test.js

Test Suites: 5 passed, 5 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        0.577 s, estimated 9 s
Ran all test suites.

> @shelf/jest-mongodb@2.2.0 test:repl
> MONGO_MEMORY_SERVER_FILE=jest-mongodb-config-repl.js jest

 FAIL  ./mongo-parallelism3.test.js
  ● parallelism: third worker › should have separate database

    MongoBulkWriteError: Primary stepped down while waiting for replication

      at handleMongoWriteConcernError (node_modules/mongodb/src/bulk/common.ts:694:5)

 PASS  ./mongo-parallelism2.test.js
 PASS  ./mongo-parallelism.test.js
 PASS  ./mongo-insert.test.js
 PASS  ./mongo-aggregate.test.js

Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        17.008 s
Ran all test suites.
```
