### ISSUE TITLE
Not working on Ubuntu 2404

### ISSUE THREAD

**Issue by ssukienn** [shelfio/jest-mongodb#479]
Same issue as for 2304 (https://github.com/shelfio/jest-mongodb/issues/455)

Fix is probably to bump memory-server - https://github.com/shelfio/jest-mongodb/pull/474

```
Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
 DownloadError: Download failed for url "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2404-6.0.9.tgz", Details:
Status Code is 403 (MongoDB's 404)
This means that the requested version-platform combination doesn't exist
Try to use different version 'new MongoMemoryServer(*** binary: *** version: 'X.Y.Z' *** ***)'
List of available versions can be found here: https://www.mongodb.com/download-center/community/releases/archive
    at RedirectableRequest.<anonymous> (/home/runner/work/ledgy-app/ledgy-app/server/node_modules/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts:383:17)
    at RedirectableRequest.emit (node:events:514:28)
    at RedirectableRequest.emit (node:domain:488:12)
    at RedirectableRequest._processResponse (/home/runner/work/ledgy-app/ledgy-app/server/node_modules/follow-redirects/index.js:409:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/home/runner/work/ledgy-app/ledgy-app/server/node_modules/follow-redirects/index.js:102:12)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:514:28)
    at ClientRequest.emit (node:domain:488:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) ***
  url: 'https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu[24](https://github.com/Ledgy/ledgy-app/actions/runs/11344616051/job/31550407709#step:4:25)04-6.0.9.tgz',
  msg: "Status Code is 403 (MongoDB's 404)\n" +
    "This means that the requested version-platform combination doesn't exist\n" +
    "Try to use different version 'new MongoMemoryServer(*** binary: *** version: 'X.Y.Z' *** ***)'\n" +
    'List of available versions can be found here: https://www.mongodb.com/download-center/community/releases/archive'
```

**Comment by tomhudak** [comment]
I wouldn't like to open yet another issue, but the same happens with Fedora 40 (anything above 34) and the fix is applied in `mongodb-memory-server` 10.1.2

**Comment by giovanni-bertoncelli** [comment]
Same issue here on a Github action runner

**Comment by Mansi1** [comment]
its not a problem with the package i think the problem is that this binary does not exist in the mongodb cdn

you can hardcode the url for now 
MONGOMS_DOWNLOAD_URL: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.9.tgz
